### ISSUE TITLE
Utilize the incremental build system supplied by Make?

### ISSUE THREAD

**Issue by PaulBatchelor** [akjmicro/dclang#5]
Is there any reason why you aren't using the incremental build features of Make?

Right now, the current program structure seems to be one "main" file, which strings together a bunch of C files via some include macros. This will mean *all* of dclang will need to be rebuilt anytime there is a change in any of the files, which piles up after a while.

With some minor restructuring of the Makefile (and possibly some tweaking of the source files), you could get a much more efficient build setup.

**Comment by akjmicro** [comment]
Hi Paul, it is almost 3 years since you wrote this message...my how time flies.

I hesitated to restructure the project, b/c it was a more significant lift than you implied. However, I gave it a go today: a dynamic lib that the final executable links to a `main.c/main.o`, and boom!

Yes it works. However, as I suspected, the non-locality of separate `*.o` files means that for instance, my simple performance benchmarks for fast loops are now TWICE (or more) as slow. So, I'm not a fan.

That said, perhaps you know of a better way to speed up performance. If you're inclined to grok the difference, do a diff against the branch known as "better_makefile_build".

I spent last weekend doing a more "all functions have a local VM struct, so locality == speed". Again, it was premature optimization to believe what I've always read. In fat, my old "globals" approach to let the compiler figure out things turned out to be slightly faster. A weekend slightly wasted, although, to be fair: I did learn a lot. One of those thing: don't believe everything you read or hear...

**Comment by PaulBatchelor** [comment]
> Yes it works. However, as I suspected, the non-locality of separate *.o files means that for instance, my simple performance benchmarks for fast loops are now TWICE (or more) as slow. So, I'm not a fan.

Interesting. I didn't factor that in when I made the initial suggestion.

> That said, perhaps you know of a better way to speed up performance. If you're inclined to grok the difference, do a diff against the branch known as "better_makefile_build".

Unfortunately, my C programming skills top off at around the "okay fast enough" benchmark. It looks like you're already doing the high-level compiler things like using "-O3".

Are you using a profiler at all? Bottlenecks can sometimes be in places you don't expect.

**Comment by akjmicro** [comment]
Closing this issue until new info comes to light that convinces me to abandon my "performance first" approach. Right now, not willing to trade-off the speed I seek for any of build conveniences mentioned, esp. since `dclang` is still so small that it builds in seconds.
